In [1]:
!git clone https://github.com/codebasics/py.git

Cloning into 'py'...
remote: Enumerating objects: 2910, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 2910 (delta 0), reused 2 (delta 0), pack-reused 2904
Receiving objects: 100% (2910/2910), 196.66 MiB | 23.20 MiB/s, done.
Resolving deltas: 100% (1121/1121), done.
Updating files: 100% (1388/1388), done.


In [2]:
ls

py/  sample_data/


In [4]:



import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
df=pd.read_csv("/content/py/ML/2_linear_reg_multivariate/homeprices.csv")

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
df.fillna(np.mean(df['bedrooms']),inplace=True)

In [11]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.2   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [15]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df[['price']])

LinearRegression()

In [16]:
reg.coef_

array([[  116.66950551, 18756.28806982, -3675.75111708]])

In [17]:
reg.intercept_

array([231586.00639409])

In [18]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[490833.34243748]])

In [19]:
reg.predict([[1500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[463236.66134653]])

we are going to predict the price of our employess based on the data of certain other employes.

In [24]:
df1=pd.read_csv("/content/py/ML/2_linear_reg_multivariate/Exercise/hiring.csv")

In [25]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [28]:
df1["test_score(out of 10)"].fillna(np.mean(df1["test_score(out of 10)"]),inplace=True)

In [29]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN               8.000000                           9      50000
1        NaN               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [34]:
word_to_number = {
'five':5,'two':2,'seven':7,'three':3,'ten':10,'eleven':11

                   }

In [35]:
df1 = df1.replace(word_to_number)

print(df1)

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN               8.000000                           9      50000
1         NaN               8.000000                           6      45000
2         5.0               6.000000                           7      60000
3         2.0              10.000000                          10      65000
4         7.0               9.000000                           6      70000
5         3.0               7.000000                          10      62000
6        10.0               7.857143                           7      72000
7        11.0               7.000000                           8      80000


In [36]:
df1.fillna(np.mean(df1['experience']),inplace=True)

In [37]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0    6.333333               8.000000                           9      50000
1    6.333333               8.000000                           6      45000
2    5.000000               6.000000                           7      60000
3    2.000000              10.000000                          10      65000
4    7.000000               9.000000                           6      70000
5    3.000000               7.000000                          10      62000
6   10.000000               7.857143                           7      72000
7   11.000000               7.000000                           8      80000

In [40]:
reg=linear_model.LinearRegression()
reg.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1['salary($)'])

LinearRegression()

In [42]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47738.89104313])

In [44]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([86424.66795913])